--- #YAML:1.0
name:                XML-DT
version:             0.50
abstract:            a package for down translation of XML files
license:             ~
author:              
    - Jose Joao <jj@di.uminho.pt>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    ExtUtils::MakeMaker:           6.17
    LWP::Simple:                   1.35
    Test::More:                    0.40
    XML::DTDParser:                2.00
    XML::LibXML:                   1.54
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
