# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-DT
version:      0.41
version_from: DT.pm
installdirs:  site
requires:
    ExtUtils::MakeMaker:           6.17
    LWP::Simple:                   1.35
    Test::More:                    0.40
    XML::DTDParser:                2.00
    XML::LibXML:                   1.54

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
