--- #YAML:1.0
name:               XML-DT
version:            0.53
abstract:           a package for down translation of XML files
author:
    - Jose Joao <jj@di.uminho.pt>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::MakeMaker:  6.17
    LWP::Simple:          1.35
    Test::More:           0.40
    XML::DTDParser:       2.00
    XML::LibXML:          1.54
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
